### ISSUE TITLE
No exception raised when YUI compressor exits with a non-zero status

### ISSUE THREAD

**Issue by jbgo** [sstephenson/ruby-yui-compressor#10]
I get an empty string when I attempt to compress a JavaScript string with a syntax error. The following is an example that reproduces the issue:

```
~$ irb
ree-1.8.7-2010.02 :001 > require 'yui/compressor'
 => true
ree-1.8.7-2010.02 :002 > YUI::JavaScriptCompressor.new.compress("var x = {class: 'name'};")
 => ""
ree-1.8.7-2010.02 :003 > exit
```

Instead, I would expect for an exception to be raised, since the YUI compressor exits with a non-zero status.

```
~$ echo "var x = {class: 'name'};" > input.js
~$ java -jar /Users/jordan/.rvm/gems/ree-1.8.7-2010.02/gems/yui-compressor-0.9.4/lib/yui/../yuicompressor-2.4.4.jar input.js 

[ERROR] 1:15:invalid property id

[ERROR] 1:0:Compilation produced 1 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
  at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:150)
  at org.mozilla.javascript.Parser.parse(Parser.java:392)
  at org.mozilla.javascript.Parser.parse(Parser.java:337)
  at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
  at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
  at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:127)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:20)
~$ echo $?
2
```

I'm using ruby enterprise edition v1.8.7 with yui-compressor gem v0.9.4.

**Comment by sstephenson** [comment]
Fixed in e24acb30b931eb26e723808c9ee1fc8e5e04dc00
